apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logging-serv103
  labels:
    app: elasticsearch-logging
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /srv/logging/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
          - serv103.threehub.net

